In [24]:
path=r'C:\Users\ankit.kumar.kothari\Desktop\step2successs-20210731T082503Z-001\step2successs\Oceane_Scripts\Inventory V1.0'
import pandas as pd
df=pd.read_excel(path+"\Export.xlsx")
df1=pd.read_excel(path+'\export_dataframe_test.xlsx')

['Sheet1']

In [18]:
# Replace using List Comphrehension
project_type=[str(i).replace("Regular MLAN Request","Ankit") for i in df['Project type']]
#project_type=[str(i).strip().lower()("Regular MLAN Request","Ankit") for i in df['Project type']]

In [19]:
#Simple white space removed
df['Project type']=df['Project type'].str.strip()

#Lambda fntn applied in df (Replace Empty cell)
df['Serial number'] =df['Serial number'].apply(lambda x: x if(str(x)!= 'nan') else "value not defined")

In [20]:
df

,Action required,Project type,Serial number,Previous\nGSK Host/Device name,Current or New\nGSK Host/Device name,Comments,Site Code,Sheet no,Equipment Manufacturer Part/Model Number,Site Name,Bus Tier,Country,Region,Category,Product Family,Management Charge-MRC- GBP,Annual management charge-GBP,Found In Inventory,Found In Archive
0,Remove,Regular MLAN Request,FDO1439X37R,NaN,evrndcare4601_1,"device not installed, should be removed from m...",EVR,SRT\Quote 459449 Evreux MLAN inventory check.xlsx,WS-C3750V2-48PS-E,Evreux,Gold,France,EMEA,SWITCH,Cisco Catalyst 3750 Series Switches,19.11,229.32,NaN,NaN
1,Remove,Regular MLAN Request,FDO1439X39A,NaN,evrndcare4601_9,"device not installed, should be removed from m...",EVR,SRT\Quote 459449 Evreux MLAN inventory check.xlsx,WS-C3750V2-48PS-E,Evreux,Gold,France,EMEA,SWITCH,Cisco Catalyst 3750 Series Switches,19.11,229.32,NaN,NaN
2,Remove,Regular MLAN Request,FOC1620V20X,NaN,evrndcare6901,"device not installed, should be removed from m...",EVR,SRT\Quote 459449 Evreux MLAN inventory check.xlsx,WS-C2960-8TC-L,Evreux,Gold,France,EMEA,SWITCH,Cisco Catalyst 2960 series switch,19.11,229.32,NaN,1.0
3,Remove,Regular MLAN Request,CAT1131NHKA,NaN,evrndcari0001,"device not installed, should be removed from m...",EVR,SRT\Quote 459449 Evreux MLAN inventory check.xlsx,WS-C3750G-24TS-S,Evreux,Gold,France,EMEA,SWITCH,Cisco Catalyst 3750 Series Switches,19.11,229.32,NaN,1.0
4,Remove,Regular MLAN Request,CAT1124ZJK4,NaN,evrndcari0002,"device not installed, should be removed from m...",EVR,SRT\Quote 459449 Evreux MLAN inventory check.xlsx,WS-C3750G-24TS-S,Evreux,Gold,France,EMEA,SWITCH,Cisco Catalyst 3750 Series Switches,19.11,229.32,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Add,Regular MLAN Request,JAD2310046R,NaN,ARA_OT_RM6,These Devices need Maintainance only,ARA,SRT\SRT 35989 Quote 459457 Burgos Aranda spai...,C9200-48T-E,Aranda,Gold,Spain,EMEA,SWITCH,Cisco Catalyst 9200 Series Switches,19.11,229.32,1.0,NaN
149,Add,Regular MLAN Request,value not defined,NaN,ARA_OT_RM7,These Devices need Maintainance only,ARA,SRT\SRT 35989 Quote 459457 Burgos Aranda spai...,C9200-48T-E,Aranda,Gold,Spain,EMEA,SWITCH,Cisco Catalyst 9200 Series Switches,19.11,229.32,1.0,NaN
150,Add,Regular MLAN Request,JAE2340194V,NaN,ARA_OT_SPARE,These Devices need Maintainance only,ARA,SRT\SRT 35989 Quote 459457 Burgos Aranda spai...,C9200-48P-E,Aranda,Gold,Spain,EMEA,SWITCH,Cisco Catalyst 9200 Series Switches,19.11,229.32,1.0,NaN
151,Add,Regular MLAN Request,value not defined,NaN,ARA_OT_SPARE,These Devices need Maintainance only,ARA,SRT\SRT 35989 Quote 459457 Burgos Aranda spai...,C9200-48P-E,Aranda,Gold,Spain,EMEA,SWITCH,Cisco Catalyst 9200 Series Switches,19.11,229.32,1.0,NaN
152,Add,Regular MLAN Request,value not defined,NaN,ARA_OT_SPARE,These Devices need Maintainance only,ARA,SRT\SRT 35989 Quote 459457 Burgos Aranda spai...,C9200-48T-E,Aranda,Gold,Spain,EMEA,SWITCH,Cisco Catalyst 9200 Series Switches,19.11,229.32,1.0,NaN

In [ ]:
#Concatinate multiple excel
df2s = pd.concat([df1,df],sort=True)
df2s

In [ ]:
# Concatinate multiple sheets withs multi tabs
for i in range(0,40):
    df=pd.read_excel("aaa",sheetname="Sheet{i}")
    df_final=pd.concat([df_final,df],sort=True)

In [25]:
#
Read Sheet Names
xl = pd.ExcelFile('foo.xls')

y=xl.sheet_names  # see all sheet names

xl.parse(sheet_name)  # read a specific sheet to DataFrame

SyntaxError: invalid syntax (Temp/ipykernel_1652/1695433416.py, line 2)

In [ ]:
# Drop Duplicates
df.drop_duplicates(subset ="Country", 
                     keep = 'first', inplace = True)

# Vlookup
df_final = pd.merge(df1,  
                      df2,  
                      on ='Country',  # column name
                      how ='left')